Make time to live configurable
AdamVig/gandi-dynamic-dns pull request #2
Opened 2021-04-29 10:35 UTC by XPlantefeve

The environment variable `TIME_TO_LIVE` can now be used to override the default ttl for the DNS record.

Bugfix: ensures IP is IPV4

2021-04-29 13:49 UTC, AdamVig requested changes
Thanks for your contribution! I requested two small changes.

2021-04-29 13:49 UTC, AdamVig commented on gandi-dynamic-dns
> +timetolive="${TIME_TO_LIVE:-3600}"
```suggestion
time_to_live="${TIME_TO_LIVE:-3600}"
```

2021-04-29 13:49 UTC, AdamVig commented on README.md
> +- `TIME_TO_LIVE`: DNS TTL, in seconds, for the subdomain (optional)
```suggestion
- `TIME_TO_LIVE`: DNS TTL, in seconds, for the record (optional)
```

2021-04-29 14:31 UTC, AdamVig reviewed
Great! I'll test this soon (later today or tomorrow), then merge it and publish a new version of the image.

2021-04-29 14:33 UTC, XPlantefeve commented
No problem, take your time. Thanks for taking it into consideration.

2021-04-30 01:20 UTC, AdamVig approved these changes
I tested this locally and found that the output looks the same as before. I tried both with and without the environment variable, so I assume it is working.

2021-04-30 01:20 UTC, merged

2021-05-01 21:32 UTC, AdamVig commented
@XPlantefeve Released on [Docker Hub](https://hub.docker.com/r/adamvig/gandi-dynamic-dns) and [GitHub Container Registry](https://github.com/users/AdamVig/packages/container/package/gandi-dynamic-dns) under the `latest` tag.